version: '2'
services:
  mongo:
    image: "mongo:3.2"
  optimizer:
    build: ./optimizer
    image: jpgouigoux/optimizer
  calc:
    build: ./calculator
    image: jpgouigoux/calculator
    environment:
      - "URLOptimizerJobs=http://optimizer/api/Jobs/"
  reporting:
    build: ./reporting
    image: jpgouigoux/reporting
  notifier:
    build: ./notifier
    image: jpgouigoux/notifier
    environment:
      - SMTP_AUTH_LOGIN=jp.gouigoux@gmail.com
      - SMTP_AUTH_PASSWORD=${GMAIL_PWD}
  app:
    build: ./portal
    image: jpgouigoux/portal
    ports:
      - "8080:8080"
