version: '2.1'
services:
  mongo:
    image: "mongo:3.2"
    ports:
      - "27017:27017"
  optimizer:
    image: jpgouigoux/optimizer
  calc:
    image: jpgouigoux/calculator
    environment:
      - "URLOptimizerJobs=http://optimizer:5004/api/Jobs/"
  reporting:
    image: jpgouigoux/reporting
  notifier:
    image: jpgouigoux/notifier
    environment:
      - SMTP_AUTH_LOGIN=jp.gouigoux@gmail.com
      - SMTP_AUTH_PASSWORD=${GMAIL_PWD}
  app:
    image: jpgouigoux/portal
    ports:
      - "8080:8080"